server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/ecommerce?currentSchema=fullstackecommerce"
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true